[POST|CODELAB]  2 Primeros post serie Construyamos una api REST con Go
gophers-latam/gophers-latam.github.io pull request #31
Opened 2024-02-10 21:46 UTC by profe-ajedrez

Estos son los 2 primeros post/codelabs de una serie de 5 que hace un walkthrough a través del proceso de construcción de una api REST.

Solicito proofreading y publicación por favor.

Siempre atento y a la escucha de comentarios, opiniones y críticas constructivas.

2024-02-11 15:56 UTC, jackgris commented on content/posts/codelab-rest-api-1/index.md
> +type IActor interface {
Otro cuestión personal, llamar las interfaces con una `I` al inicio, para mi gusto es muy de Java y no así de Go. Volvemos a lo personal.

2024-02-11 16:00 UTC, jackgris commented on content/posts/codelab-rest-api-2/index.md
> +func BenchmarkActorGetByID(b *testing.B) {
Me gusta que le hayas agregado un `Benchmark` eso no se suele tocar mucho en cursos iniciales, pero es algo muy importante en el desarrollo.

2024-02-11 16:02 UTC, jackgris approved these changes
Excelente par de artículos, los únicos comentarios que hice terminan siendo en su mayoría apreciaciones y gustos personales. Muy buen material para la comunidad.

2024-02-11 16:12 UTC, areyes-bsale commented on content/posts/codelab-rest-api-1/index.md
> +type IActor interface {
Entiendo, y me parece super válido. Por eso aclaro en el mismo texto que los nombres usados n o se deben a ninguna práctica y solo son para diferenciar las estructuras de datos. ¿Te parece si en el último artículo de la serie, donde volvamos a tocar el tema de las oponiones reforzamos esto?

2024-02-13 15:45 UTC, ThiagoMowszet approved these changes

2024-02-16 00:21 UTC, Sirpyerre commented on content/posts/codelab-rest-api-2/index.md
> +Si le gustó este artículo no olvide compartirlo, y si después de seguirlo le quedan dudas o preguntas le esperamos en los ocmentarios.
Aquí un typo: `ocmentarios.`

2024-02-16 00:34 UTC, Sirpyerre requested changes
Hola te dejo unos comentarios, me enfoque en la ortografía más que nada. Espero sean de ayuda mis observaciones.

2024-02-16 00:34 UTC, Sirpyerre commented on content/posts/codelab-rest-api-2/index.md
> +cómo habíamos construido también un benchmark para `MockActorCrud` Podemos ejecutarlo también y tener una idea del costo verdadero de nuestro flujo.
El inicio del párrafo con mayúsculas y el `Podemos ejecutarlo` la `p` con minúsculas.

2024-02-16 00:34 UTC, Sirpyerre commented on content/posts/codelab-rest-api-2/index.md
> +Hablamos de *simular peticiones* porque nuestra aplicación no necesitará estar ejecutándose cuando gatillemos los tests, recordemos que estos deben ser [aislados, independientes y auto validantes](ht
La palabra `gatillemos` me llama la atención, pero igual es algo mío porque no la uso. Quizá podemos usar una palabra más neutra como `iniciemos`.

2024-02-16 00:34 UTC, Sirpyerre commented on content/posts/codelab-rest-api-2/index.md
> +Definimos una interface que expone el método `Do`, el cual recibe cómo argumento un request y devuelve una respuesta y el posible error gatillado durante el procesamiento de la petición.
Pienso que es mejor sustituir `gatillado` por `ocurrido`

2024-02-16 00:34 UTC, Sirpyerre commented on content/posts/codelab-rest-api-2/index.md
> +Construimos un struct que *implementa* dicha interface. En este struct definimos una variable de tipo función que será invocada cuando se llame al método expuesto en el struct. así podemos cargar la
Después del punto, iniciar con mayúscula después del struct.

2024-02-16 23:07 UTC, Sirpyerre approved these changes

2024-02-19 15:24 UTC, profe-ajedrez commented
Después de pensarlo mucho, quizás el producir un artículo sobre este tema debería ser un proyecto comunitario organizado, Por eso cierro el pull request.

2024-02-19 15:24 UTC, closed without merging