update bot page project content
gophers-latam/gophers-latam.github.io pull request #42
Opened 2024-08-07 13:05 UTC by zeroidentidad

Se incluyo un enlace de nuevo video en el texto del contenido como se habia comentado

2024-08-07 21:05 UTC, ThiagoMowszet requested changes
@zeroidentidad gracias por la PR. Te deje como sugerencia unos comentarios.

2024-08-07 21:05 UTC, ThiagoMowszet commented on content/proyectos/gopherbot.md
> +- **Estatus:** El bot se encuentra activo y disponible para el servidor de Discord de la comunidad. Su sitio informativo y formulario para enviar desafios es: https://gopherbot.onrender.com/
En anteriores proyecto pusimos `Status`. Ver si quedaria asi, sino cambiarlo en el resto.

2024-08-07 21:05 UTC, ThiagoMowszet commented on content/proyectos/gopherbot.md
> +*Demostración de uso de los comandos disponibles a la fecha del ➡ [video compartido](https://youtube.com/watch?v=ZGlV6N12oy8)
No estaria bueno agregar un parrafo mas, dejando tambien el video mas largo para que el que quiera desarrollar en el, pueda verlo? lo digo como sugerencia!

2024-08-08 13:59 UTC, zeroidentidad commented on content/proyectos/gopherbot.md
> +- **Estatus:** El bot se encuentra activo y disponible para el servidor de Discord de la comunidad. Su sitio informativo y formulario para enviar desafios es: https://gopherbot.onrender.com/
modificado

2024-08-08 13:59 UTC, zeroidentidad commented on content/proyectos/gopherbot.md
> +*Demostración de uso de los comandos disponibles a la fecha del ➡ [video compartido](https://youtube.com/watch?v=ZGlV6N12oy8)
![nah](https://github.com/user-attachments/assets/917ee53f-59d2-4646-8406-a6d4b5e0cdd2)

2024-08-08 15:27 UTC, ThiagoMowszet approved these changes

2024-08-08 15:27 UTC, merged